name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ FeedbackApp-${{ steps.date.outputs.date }} }}
          release_name: ${{ FeedbackApp-${{ steps.date.outputs.date }} }}
          draft: false
          prerelease: false
