name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: FeedbackApp-${{ steps.date.outputs.date }}
          release_name: FeedbackApp-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
  Export-solution-Feedback:
    needs: [ build ]
    uses: ./.github/workflows/export-and-branch-solution.yml
    with:
      #You can specify the solution name here
      solution_name: PowerPlatformDevopsSolution
      solution_exported_folder: out/exported/
      solution_folder: out/solutions/
      solution_target_folder: solutions/
      BUILD_ENVIRONMENT_URL: https://org81cb9f70.crm6.dynamics.com/
      CLIENT_ID: 291adacd-5854-4cd4-be80-558cfe4e4dbf
      TENANT_ID: 3501e278-e6f5-4e0b-a897-abfa9b1c4136 
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}

  Release-solution-Feedback:
    needs: [ Export-solution-Feedback ]
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: PowerPlatformDevopsSolution
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org81cb9f70.crm6.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://orgd0989e10.crm6.dynamics.com
      CLIENT_ID: 291adacd-5854-4cd4-be80-558cfe4e4dbf
      TENANT_ID: 3501e278-e6f5-4e0b-a897-abfa9b1c4136    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
